# Generated by Django 4.2.2 on 2023-12-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DersAdi', models.CharField(max_length=200)),
                ('DersKodu', models.CharField(max_length=20)),
                
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('Ad', models.CharField(max_length=200)),
                ('Soyad', models.CharField(max_length=200)),
                ('Cinsiyet', models.CharField(max_length=10)),
                ('Bolum', models.CharField(max_length=50)),
                ('Sinif', models.CharField(max_length=5)),
                ('Numara', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OgretimGorevlisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad', models.CharField(max_length=200)),
                ('Soyad', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                
            ],
        ),
        migrations.CreateModel(
            name='OgretimGorevlisi_Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDTBMProject.dersler')),
                ('ogretimGorevlisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDTBMProject.ogretimgorevlisi')),

            ],
        ),
        migrations.CreateModel(
            name='Ogrenci_Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDTBMProject.dersler')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDTBMProject.ogrenci')),
            ],
        ),
    ]
