# Generated by Django 4.2.2 on 2023-12-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDTBMProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ogrenci_Ders',
            new_name='Kayit',
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='Ad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='Soyad',
            field=models.CharField(max_length=50),
        ),
    ]
